import type { Metadata } from "next";
import { Bricolage_Grotesque, Gochi_Hand, Onest } from "next/font/google";
import "@/styles/main.css";

const display = Bricolage_Grotesque({
  subsets: ["latin"],
  axes: ["opsz"], // wght is always included; opsz drives headline vs. small-text rendering
  display: "swap",
  variable: "--font-display",
});

const text = Onest({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-text",
});

const brand = Gochi_Hand({
  subsets: ["latin"],
  weight: "400", // static family — weight is required
  display: "swap",
  variable: "--font-brand",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${display.variable} ${text.variable} ${brand.variable}`}
    >
      <body>{children}</body>
    </html>
  );
}
